From 3e748373067536c21275d7d8d0b4e86f644def79 Mon Sep 17 00:00:00 2001
From: Xiretza <xiretza@xiretza.xyz>
Date: Wed, 2 Apr 2025 20:32:06 +0000
Subject: [PATCH] Fix radicale compatibility

discover() was changed in v3.3.0:

https://github.com/Kozea/Radicale/commit/d1ceb620e4d416250c5218bfd0d2bb6de72af11e
---
 etesync_dav/radicale/storage.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/etesync_dav/radicale/storage.py b/etesync_dav/radicale/storage.py
index 4eff0b3..ef5885f 100644
--- a/etesync_dav/radicale/storage.py
+++ b/etesync_dav/radicale/storage.py
@@ -501,7 +501,7 @@ class Storage(BaseStorage):
         self._etesync_user_lock = threading.RLock()
         super().__init__(configuration)
 
-    def discover(self, path, depth="0"):
+    def discover(self, path, depth="0", child_context_manager = None, user_groups = set([])):
         """Discover a list of collections under the given ``path``.
 
         If ``depth`` is "0", only the actual object under ``path`` is
-- 
2.49.0

